-- Crie uma stored procedure que adicione um sinistro (inserir uma linha), passando todas as informações
-- necessárias para se cadastrar um sinistro, como parâmetros de entrada. Validar antes de cadastrar o
-- sinistro, se o carro existe. Caso exista, prosseguir com o INSERT. Caso não exista, informar via PRINT que o
-- carro não existe. 
-- A lista da stored procedures deverá ter as seguintes colunas:
-- Nome do curso, ranking, qt_aluno
-- A coluna qt_sinistro deverá possuir a quantidade de alunos relativos ao curso